//go:build linux

package dns

import (
	"context"
	"os"
	"os/exec"
	"strings"
	"time"
)

type linuxManager struct{}

func NewManager() (Manager, error) {
	return &linuxManager{}, nil
}

func execOut(name string, args ...string) ([]byte, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	return exec.CommandContext(ctx, name, args...).Output()
}

func (m *linuxManager) getActiveInterface() (string, error) {
	out, err := execOut("sh", "-c", "ip route show default 2>/dev/null | awk '{print $5}'")
	if err == nil {
		iface := strings.TrimSpace(string(out))
		if iface != "" {
			return iface, nil
		}
	}
	return "eth0", nil
}

func (m *linuxManager) SetDNS(servers []string) error {
	iface, err := m.getActiveInterface()
	if err != nil {
		return err
	}

	if _, err := exec.LookPath("resolvectl"); err == nil {
		for _, s := range servers {
			ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
			exec.CommandContext(ctx, "resolvectl", "dns", iface, s).Run()
			cancel()
		}
		return nil
	}

	if _, err := exec.LookPath("nmcli"); err == nil {
		exec.Command("nmcli", "con", "mod", iface, "ipv4.ignore-auto-dns", "yes").Run()
		exec.Command("nmcli", "con", "mod", iface, "ipv4.dns", strings.Join(servers, " ")).Run()
		exec.Command("nmcli", "con", "down", iface).Run()
		exec.Command("nmcli", "con", "up", iface).Run()
		return nil
	}

	content := ""
	for _, s := range servers {
		content += "nameserver " + s + "\n"
	}

	return os.WriteFile("/etc/resolv.conf", []byte(content), 0644)
}

func (m *linuxManager) RemoveDNS() error {
	iface, err := m.getActiveInterface()
	if err != nil {
		return err
	}

	if _, err := exec.LookPath("resolvectl"); err == nil {
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		exec.CommandContext(ctx, "resolvectl", "dns", iface, "").Run()
		cancel()
		ctx2, cancel2 := context.WithTimeout(context.Background(), 5*time.Second)
		exec.CommandContext(ctx2, "resolvectl", "flush", "caches").Run()
		cancel2()
		return nil
	}

	if _, err := exec.LookPath("nmcli"); err == nil {
		exec.Command("nmcli", "con", "mod", iface, "ipv4.ignore-auto-dns", "no").Run()
		exec.Command("nmcli", "con", "mod", iface, "--", "ipv4.dns", "").Run()
		exec.Command("nmcli", "con", "down", iface).Run()
		exec.Command("nmcli", "con", "up", iface).Run()
		return nil
	}

	content := "# Generated by DNS Changer\n"
	return os.WriteFile("/etc/resolv.conf", []byte(content), 0644)
}

func (m *linuxManager) GetCurrentDNS() ([]string, error) {
	iface, err := m.getActiveInterface()
	if err != nil {
		return []string{}, nil
	}

	if _, err := exec.LookPath("resolvectl"); err == nil {
		out, err := execOut("resolvectl", "dns", iface)
		if err == nil {
			line := strings.TrimSpace(string(out))
			parts := strings.Fields(line)
			servers := []string{}
			for _, p := range parts {
				if strings.Count(p, ".") == 3 || strings.Contains(p, ":") {
					servers = append(servers, p)
				}
			}
			if len(servers) > 0 {
				return servers, nil
			}
		}
	}

	if _, err := exec.LookPath("nmcli"); err == nil {
		out, err := execOut("nmcli", "-t", "dev", "show", iface)
		if err == nil {
			for _, line := range strings.Split(string(out), "\n") {
				if strings.HasPrefix(line, "IP4.DNS[") {
					parts := strings.SplitN(line, ":", 2)
					if len(parts) == 2 {
						return []string{strings.TrimSpace(parts[1])}, nil
					}
				}
			}
		}
	}

	data, err := os.ReadFile("/etc/resolv.conf")
	if err != nil {
		return []string{}, nil
	}
	servers := []string{}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "nameserver") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				servers = append(servers, parts[1])
			}
		}
	}
	return servers, nil
}

func (m *linuxManager) GetActiveInterface() (string, error) {
	return m.getActiveInterface()
}
