// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProfile(arg1, arg2) {
  return window['go']['main']['App']['AddProfile'](arg1, arg2);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function GetActiveInterface() {
  return window['go']['main']['App']['GetActiveInterface']();
}

export function GetCurrentDNS() {
  return window['go']['main']['App']['GetCurrentDNS']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function PingServer(arg1) {
  return window['go']['main']['App']['PingServer'](arg1);
}

export function RemoveDNS() {
  return window['go']['main']['App']['RemoveDNS']();
}

export function ReorderProfiles(arg1) {
  return window['go']['main']['App']['ReorderProfiles'](arg1);
}

export function SetDNS(arg1) {
  return window['go']['main']['App']['SetDNS'](arg1);
}

export function UpdateProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2, arg3);
}
