// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {profiles} from '../models';
import {pinger} from '../models';

export function AddProfile(arg1:string,arg2:Array<string>):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function GetActiveInterface():Promise<string>;

export function GetCurrentDNS():Promise<Array<string>>;

export function GetPlatform():Promise<string>;

export function GetProfiles():Promise<Array<profiles.Profile>>;

export function PingServer(arg1:string):Promise<pinger.Result>;

export function RemoveDNS():Promise<void>;

export function ReorderProfiles(arg1:Array<string>):Promise<void>;

export function SetDNS(arg1:Array<string>):Promise<void>;

export function UpdateProfile(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;
